### ISSUE TITLE
App 1.0.1 not loading in Nextcloud 22.2.3

### ISSUE THREAD

**Issue by kolewu** [mziech/nextcloud-majordomo#19]
I have installed the app and now it's visible in the menu of the nextcloud admin. When I choose it from there it only shows _"Loading"_ and nothing happens.
![image](https://user-images.githubusercontent.com/95135/149392705-088a502c-132b-40aa-9b37-eba78809f292.png)

In the browser console of chromium 96 there are two not really informative errors about a 404 from `/apps/majordomo/api/lists`:
![image](https://user-images.githubusercontent.com/95135/149393072-6f69482e-fe70-4468-8e3b-06676c401ed4.png)

There is nothing in the nextcloud log.

I don't know what I can do now to get more information for helping make it work.

**Comment by kolewu** [comment]
Wow, that's fast. Thankyou!

With version 1.0.2 the app now loads. But I don't understand what this may have to do with rewrite? The default rewrite rules in `.htaccess` are working, as far as I can see. So the dashboard is available with `/index.php/apps/dashboard/` but also without `index.php` with `/apps/dashboard/` and to test one of the rules `/.well-known/caldav` happily is rewritten to `/remote.php/dav/`. What am I missing?

**Comment by mziech** [comment]
Glad that 1.0.2 fixes your issue, it was more of a hunch!

From my experience, .htaccess is not (always) updated when you update Nextcloud, so if you have an installation with long history, it might be that the .htaccess is a little bit outdated. Also, judging from https://github.com/nextcloud/server/blob/0d0fcd316a6b556cabf656cd7bdca63da26aab2d/lib/private/Template/JSConfigHelper.php#L200, Nextcloud detects whether rewrite is working based on an environment variable. So e.g. if mod_env is missing, that enviroment variable is not set while mod_rewrite is working perfectly, `'htaccess.IgnoreFrontController' => true` may help in that case.

But I'm just guessing here. The app was not behaving 100% correctly, that is fixed :)
