### ISSUE TITLE
Build instructions don't work with docker

### ISSUE THREAD

**Issue by kolewu** [mziech/nextcloud-majordomo#21]
The instructions for building the app with docker, are not working:
```
npm ERR! missing script: dist
```
And in fact, there is no build script `dist` in `package.json`. Without this I would suspect that the "normal" build will fail, too.
I'm even not sure what the docker build should produce: It builds a container with the build result in it (if it succeeds), but how to get to it?

Without a dedicated build script, one could use the `node:12` image to build something without installing node and npm on the local machine:
```
docker run -it --rm -v $(pwd):/work -w /work node:12 \
    bash -c "npm install && npm run build"
```
Replace `npm run build` with `npm run dist` if there is a proper `dist`script that I think is supposed to create `majordomo.tar.gz`.

**Comment by mziech** [comment]
You're right, I removed the `dist` script while migrating to Github actions and forgot to update the documentation. The tar.gz is now built [inside the Github action](https://github.com/mziech/nextcloud-majordomo/blob/main/.github/workflows/release.yml#L21) itself. Also, as you pointed out, the Docker *container* is not really helpful, I'll remove it and will add something like your example to the README.
