### ISSUE TITLE
The app could only be used by admins

### ISSUE THREAD

**Issue by kolewu** [mziech/nextcloud-majordomo#25]
I normally don't use my cloud accounts as admin, so to use this app I have to switch the user. This also means, that I can't give other users the right, to operate on their mailinglist.

Is there anything dangerous about the background jobs accessing the IMAP-account? If not, I would like to have the option to make the mailinglist configuration available to some users or a group of users.

It's in the current configuration with a single IMAP-account for the whole instance only reasonable for private use, but that's exactly my usecase: Give some family-members the opportunity to control the subscription lists of their own mailinglists without having to learn how to do this by sending emails to _majordomo_ -- and without bothering me 😉

**Comment by mziech** [comment]
Hmm, I guess that will require
- unlocking the menu item for all users in `appinfo.xml`
- adding a UI for permission management (e.g. specify sub-admin for each list)
- modify `ApiController` to check fine grained permissions

Not impossible but also not a straight forward change to do ...

**Comment by mziech** [comment]
Looks like Nextcloud 23 introduced admin-rights delegation. The implementation looks rather straight forward, e.g. in logreader:
https://github.com/nextcloud/logreader/commit/c875e6ccb065e131621dae0122e1cbbded30c106

Maybe this is a good intermediate solution.

**Comment by kolewu** [comment]
Yes, this looks very promising. But if I understand it, it's only working for "real" settings pages, that appear under "Adminstration" in the Settings where normal users only have "Personal".
See [Admin right privilege](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/admin_delegation_configuration.html)

**Comment by mziech** [comment]
Yes, I tinkered a bit with the API and I got the app registered even without a settings page. The problem then is the missing menu button. Converting the UI to a settings-page may be difficult since the navigation bar is already used otherwise. So, I'm now looking into implementing the promised ACL concept after all ...

**Comment by mziech** [comment]
With 2.0.0 #46 the menu item is now displayed for all users. Mailinglist can still only be created by admins but permissions of mailing lists can be delegated to moderator/admin users.
