### ISSUE TITLE
App Store Install Fails: "payload" is type String, but exceeding the 4.000 length limit.

### ISSUE THREAD

**Issue by Seriousness** [mziech/nextcloud-majordomo#31]
When trying to add the app via the appstore an error message is shown and the app is not installed:

`Column "u3YTI_majordomo_requests"."payload" is type String, but exceeding the 4.000 length limit. `

**Comment by mziech** [comment]
Which Nextcloud version and database are you using?

**Comment by Seriousness** [comment]
Main system:
NC 24.0.4 
MariaDB 10.5.16

Tried it on multiple instances, same error.

**Comment by mziech** [comment]
Something must have changed in the database migration code. But the payload column is not really used, so I could safely reduce the size, it will be dropped in a later release. Thanks for the heads-up!
