### ISSUE TITLE
Now is easier to maintain compatibility with newer Nextcloud releases

### ISSUE THREAD

**Issue by p-bo** [mziech/nextcloud-majordomo#34]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by mziech** [comment]
Thanks good to know! Of course, I hope that Nextcloud finds the right balance between compatibility, documentation and innovation. A Nextcloud 25 compatible version is prepared but the UI changes of that release require some further testing.

**Comment by p-bo** [comment]
Glad to help :-) Thank you for updating for newest Nextcloud!

**Comment by mziech** [comment]
Noted and fixed Nextcloud 25 compatibility with 1.1.3.
