### ISSUE TITLE
Feature Request: Add Scrollbar when working with larger mailing lists

### ISSUE THREAD

**Issue by citrixguyblog** [mziech/nextcloud-majordomo#38]
Hello Marco,
thanks for creating the Majordomo app. We are working with some mailing lists with 15 and more subscribers and its getting difficult to manage due a missing scrollbar. The scrollbar is missing for both frames (current members and member policy).
Would be great to see this enhancement in a newer version.

**Comment by mziech** [comment]
Hi @citrixguyblog,
interesting catch, I think there used to be scrollbars at some point. Maybe they got removed during some design upgrade ...

**Comment by citrixguyblog** [comment]
Hi Marco, it would be great if you have some time to have a look why it got removed. The app looks really promising in managing mailing lists for a non-profit organization I am helping with simplifying the administration.

**Comment by mziech** [comment]
It is a compatibility issue with the `@nextcloud/vue` component. I'll upgrade it with the next release which I'm currently preparing for Nextcloud 28 compatibility.

**Comment by citrixguyblog** [comment]
That sounds great. Thanks a lot!

**Comment by mziech** [comment]
Fixed in 1.2.0
